name: Build HB Store

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devkitPro
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://apt.devkitpro.org/install-devkitpro-pacman
