- name: Install devkitPro (FIX)
  run: |
    sudo apt update
    sudo apt install -y git wget

    git clone https://github.com/devkitPro/pacman.git
    cd pacman
    sudo bash ./install.sh

    sudo dkp-pacman -Syu --noconfirm
    sudo dkp-pacman -S --noconfirm devkitARM 3ds-dev
