name: Build HB Store

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup devkitPro
        run: |
          sudo apt update
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm devkitARM 3ds-dev

      - name: Build
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=$DEVKITPRO/devkitARM
          make

      - uses: actions/upload-artifact@v3
        with:
          name: yoshihbstore
          path: "*.3dsx"
